title: YAMAN SOUND
description: Prague drum & bass events and YAMAN Recordings.
url: https://yamansound.eu
baseurl: ""
lang: en
markdown: kramdown

# DŮLEŽITÉ:
# umožní generovat stránky eventů s budoucím datem
future: true

collections:
  events:
    output: true
    permalink: /:name.html

  crew:
    output: true
    permalink: /artists/:name.html

  sound_posts:
    output: true
    permalink: /:name.html

  media_posts:
    output: false

defaults:
  - scope:
      path: ""
      type: events
    values:
      layout: event
      nav: events

  - scope:
      path: ""
      type: crew
    values:
      layout: artist
      nav: crew

  - scope:
      path: ""
      type: sound_posts
    values:
      layout: sound_post
      nav: sound

exclude:
  - README.txt
  - README-CMS.md
  - Gemfile
  - Gemfile.lock